name: Push Docker Image to Docker Hub # 워크플로우 이름

on: # 동작 조건
  push: # 브랜치 또는 태그가 푸시될 때 실행
    branches:
      - 'main' # master 브랜치에 한정
    tags:
      - '**' # 모든 태그에 대해 실행

jobs: # 작업 정의
  push: # 작업 이름
    runs-on: ubuntu-latest # 실행할 환경 설정

    steps: # 단계 정의
      - name: Checkout # 저장소 코드 다운로드
        uses: actions/checkout@v2 # 특정 브랜치로 체크아웃

      - name: Docker meta # Docker 메타데이터 설정
        id: docker_meta # 하위 단계에서 사용될 ID
        uses: crazy-max/ghaction-docker-meta@v1 # 도커 메타데이터 동작
        with:
          images: dongjukim123/ci-test # 사용할 Docker 리포지토리
          tag-semver: | # 태그로 사용할 버전 정보
            {{version}}
            {{major}}.{{minor}}

      - name: Set up QEMU # QEMU 설정
        uses: docker/setup-qemu-action@v2 # 다양한 플랫폼에서 실행 가능

      - name: Set up Docker Buildx # Docker Buildx 설정
        uses: docker/setup-buildx-action@v2 # 다른 플랫폼용 빌드 지원

      - name: Login to Docker Hub # Docker Hub 로그인
        uses: docker/login-action@v2 # 로그인 동작
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} # 사용자 ID 비밀값
          password: ${{ secrets.DOCKER_HUB_PASSWORD }} # 사용자 비밀번호 비밀값

      - name: Build and push Docker Image # Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v4
        with:
          context: . # 빌드 컨텍스트 설정
          push: true # 빌드 후 푸시 여부
          tags: ${{ steps.docker_meta.outputs.tags }} # 메타데이터에서 태그 사용
          labels: ${{ steps.docker_meta.outputs.labels }} # 메타데이터에서 레이블 사용
